### ISSUE TITLE
How to detach hook? [in frida detachAll]

### ISSUE THREAD

**Issue by Xset-s** [jmpews/HookZz#20]
How to detach hooks or single hook? Frida has special method - "Interceptor.detachAll();".

**Comment by jmpews** [comment]
at my local branch, I will merge it to master soon. Thanks for your issue.




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：jmpews@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
On 01/31/2018 03:55, Anton Shadrin wrote: How to detach hook? Frida has special method - "Interceptor.detachAll();".

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jmpews/HookZz","title":"jmpews/HookZz","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jmpews/HookZz"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How to detach hook? [in frida detachAll] (#20)"}],"action":{"name":"View Issue","url":"https://github.com/jmpews/HookZz/issues/20"}}}

**Comment by jmpews** [comment]
at my local branch, I will merge it to master soon. Thanks for your issue.

**Comment by Xset-s** [comment]
Thx 👍

**Comment by Xset-s** [comment]
Meeerrgee plzz. I really need detach c:

**Comment by jmpews** [comment]
@Xset-s sorry fo that, tomorrow will be OK.

**Comment by Xset-s** [comment]
thxx)) Is it avaliable for armv7 or anly for arm64? I need to write ZzDisableHook(addr)?

**Comment by jmpews** [comment]
@Xset-s it should be fine for armv7 and arm64, but i just test for arm64. if crashed, please let me known, i will fix it.

**Comment by Xset-s** [comment]
First of all, can you add new function "HookDetackGOT" to "backend-linux" platform? I see this function only for darwin platform :c

**Comment by Xset-s** [comment]
telegram, @XsetOfficial
